version: '3'

services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_ENABLED=${JWT_ENABLED}
      - JWT_SECRET=${JWT_SECRET}
